### ISSUE TITLE
Editor crashes when viewing PKGBUILD

### ISSUE THREAD

**Issue by wordmage** [kriansa/pacom#1]
While adding a package from AUR, I encountered errors that seem to stem from faulty stdin. This error crops up during the 'Downloading PKGBUILD' section, where the editor is expected to view(?) the file. The error varies from editor to editor, but I was able to capture the one from `vim` and `nano` (respectively), which are:

```
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
```

and:

`Too many errors from stdin`

These errors can be reproduced in both editors, even when tested under two different shells: `bash` and `oksh`. There is no difference in behaviour for either shell or editor.

---

I tried to dig the cause to the issue and have found that when [this invocation of `$EDITOR`](https://github.com/kriansa/pacom/blob/main/lib/cmds/add.sh#L111) is changed from `-R` to `-`, both `vim` and `nano` behave as expected (PKGBUILD is viewed and no crash is seen). Was there a particular reason to use `-R` here in place of the usual `-`?

Other than the assumption above, I have also tried to reinstall pacom from AUR as well as compiling my own from this repository with no change; reinstalling fails to resolve this issue.

---

My machine uses the following:
- Arch, latest update as of time of writing
- `oksh` 7.0 and `bash` 5.1.8
- `urvxt` for terminal
- `vim` 8.2 and `nano` 5.9
- `pacom` 1.0.5

**Comment by kriansa** [comment]
Ops, this is not good. Thanks for digging into this issue :+1: 

In fact, the usage of `-R` is not in replacement of `-`, but to tell `vim` that we don't want to save that file (it's read-only). But that was naive on my part, simply because:

1. I use `nvim` and it works, so I assumed `vim` would work fine with the same parameters... rookie mistake
2. This should never be assumed because I was not invoking `vim`, but `$EDITOR`, and that could be anything, really.

So yeah, the fix should definitely be a change to `$EDITOR -` instead, because the only assumption we can have regarding text editors is that most of them will take whatever input you send at `stdin`. I'll publish that in a few.

Now regarding your uninstall issue, can you post the commands you're trying to use and the error messages you get?

**Comment by kriansa** [comment]
@wordmage I just published a fix on `v1.0.6`. Could you try it and let me know?

**Comment by wordmage** [comment]
I will try it out soon, thank you for the prompt response!

Re: the 'installation issue', I believe I didn't phrase well what I meant. What I mean by 'reinstalling fails to resolve this issue' was that reinstalling pacom doesn't solve the editor crash, which did indicate that the issue was not due to any faulty installation (or at least, hopefully it wasn't).

However, now I'm a bit curious as to decision to use `EDITOR` here. Is there any intention to edit the PKGBUILD before the user adds it to their repository? Or is viewing more of the intended purpose? If pacom's goal is to let user preview the PKGBUILD then wouldn't it be better to pipe the PKGBUILD to `PAGER` instead?

**Comment by wordmage** [comment]
I've built 1.0.6 and I can confirm that the issue no longer exists on my end. I ran the commands which I used to reproduce the issue (`pacom add`) and it now works as expected. We can mark this issue as solved if no more discussion is necessary.

**Comment by kriansa** [comment]
Glad to hear it worked! :+1: 

> However, now I'm a bit curious as to decision to use `EDITOR` here. Is there any intention to edit the PKGBUILD before the user adds it to their repository? Or is viewing more of the intended purpose? If pacom's goal is to let user preview the PKGBUILD then wouldn't it be better to pipe the PKGBUILD to `PAGER` instead?

Initially, I considered piping to `PAGER`, but at that point, I wasn´t happy with the syntax highlighting, and with an actual text editor you will not only be able to get syntax highlighting but you have better navigation features such as find by name, jump between functions and so on. I'm not aware of any pager that supports that, and that's why I decided to stick with `EDITOR` instead.

I'll close this but feel free to reopen if you want.
